/**
 * Source: KSRTC Subrahmanya Bus Stand (ಸುಬ್ರಹ್ಮಣ್ಯ ಬಸ್ ನಿಲ್ದಾಣ)
 * Origin of all departures: Subrahmanya
 */
const TIMETABLE_DATA = {
  station: {
    name_en: "Subrahmanya Bus Stand",
    name_kn: "ಸುಬ್ರಹ್ಮಣ್ಯ ಬಸ್ ನಿಲ್ದಾಣ",
    operator: "Karnataka State Road Transport Corporation (KSRTC / ಕ.ರಾ.ರ.ಸಾ.ನಿ.)"
  },
  routes: [
    {
      id: "bengaluru",
      destination_en: "Bengaluru",
      destination_kn: "ಬೆಂಗಳೂರು",
      platform: "1, 2, 3",
      bus_type: "Express / Karnataka Sarige / Ashwamedha / Rajahamsa / Non-AC Sleeper",
      departures: [
        { time: "05:00", type: "Karnataka Sarige" },
        { time: "06:00", type: "Karnataka Sarige" },
        { time: "07:00", type: "Karnataka Sarige" },
        { time: "08:00", type: "Karnataka Sarige" },
        { time: "08.15", type: "Karnataka Sarige" },
        { time: "08:30", type: "Karnataka Sarige" },
        { time: "09:30", type: "Karnataka Sarige" },
        { time: "10:00", type: "Karnataka Sarige" },
        { time: "10:15", type: "Karnataka Sarige" },
        { time: "10:20", type: "Karnataka Sarige" },
        { time: "10:40", type: "Karnataka Sarige" },
        { time: "11:00", type: "Karnataka Sarige" },
        { time: "11:30", type: "Karnataka Sarige" },
        { time: "11:45", type: "Karnataka Sarige" },
        { time: "12:00", type: "Karnataka Sarige" },
        { time: "12:30", type: "Karnataka Sarige" },
        { time: "13:00", type: "Karnataka Sarige" },
        { time: "13:15", type: "Karnataka Sarige" },
        { time: "13:20", type: "Karnataka Sarige" },
        { time: "13:30", type: "Karnataka Sarige" },
        { time: "13:45", type: "Karnataka Sarige" },
        { time: "14:15", type: "Karnataka Sarige" },
        { time: "14:30", type: "Rajahamsa" },
        { time: "14:50", type: "Karnataka Sarige" },
        { time: "15:15", type: "Karnataka Sarige" },
        { time: "15:45", type: "Karnataka Sarige" },
        { time: "16:15", type: "Karnataka Sarige" },
        { time: "16:45", type: "Karnataka Sarige" },
        { time: "17:00", type: "Karnataka Sarige" },
        { time: "17:30", type: "Karnataka Sarige" },
        { time: "18:15", type: "Ashwamedha" },
        { time: "19:00", type: "Karnataka Sarige" },
        { time: "19:30", type: "Karnataka Sarige" },
        { time: "20:00", type: "Karnataka Sarige" },
        { time: "20:30", type: "Karnataka Sarige" },
        { time: "21:21", type: "Karnataka Sarige" },
        { time: "21:35", type: "Ashwamedha" },
        { time: "21:50", type: "Karnataka Sarige" },
        { time: "21:55", type: "Karnataka Sarige" },
        { time: "22:00", type: "Karnataka Sarige" },
        { time: "22:10", type: "Karnataka Sarige" },
        { time: "22:16", type: "Karnataka Sarige" },
        { time: "22:25", type: "Karnataka Sarige" },
        { time: "22:34", type: "Karnataka Sarige" }
      ]
    },
    {
      id: "mysuru",
      destination_en: "Mysuru",
      destination_kn: "ಮೈಸೂರು",
      platform: "4",
      bus_type: "Vegadhootha / Express",
      departures: [
        { time: "12:45", type: "Express" },
        { time: "14:00", type: "Express" },
        { time: "14:45", type: "Express" },
        { time: "15:15", type: "Express" },
        { time: "16:15", type: "Express" },
        { time: "17:30", type: "Express" },
        { time: "20:00", type: "Express" },
        { time: "21:00", type: "Express" },
        { time: "22:00", type: "Express" }
      ]
    },
    {
      id: "shivamogga",
      destination_en: "Shivamogga",
      destination_kn: "ಶಿವಮೊಗ್ಗ",
      platform: "5",
      bus_type: "Vegadhootha / Express",
      departures: [
        { time: "04:45", type: "Express" },
        { time: "05:15", type: "Express" },
        { time: "06:15", type: "Express" },
        { time: "11:05", type: "Express" },
        { time: "14.30", type: "Express" },
        { time: "17:30", type: "Express" },
        { time: "18:00", type: "Express" },
        { time: "19:00", type: "Express (Ballary / ಬಳ್ಳಾರಿ)" },
        { time: "20:30", type: "Express (Davangere / ದಾವಣಗೆರೆ)" }
      ]
    },
    {
      id: "dharmasthala",
      destination_en: "Dharmasthala",
      destination_kn: "ಧರ್ಮಸ್ಥಳ",
      platform: "5, 6, 7",
      bus_type: "Vegadhootha / Express",
      departures: [
        { time: "04:45", type: "Express" },
        { time: "05:15", type: "Express" },
        { time: "05:30", type: "Express" },
        { time: "06:15", type: "Express" },
        { time: "07:00", type: "Express" },
        { time: "07:15", type: "Express" },
        { time: "07:45", type: "Express" },
        { time: "08:00", type: "Express" },
        { time: "08:20", type: "Express" },
        { time: "08:45", type: "Express" },
        { time: "09:45", type: "Express" },
        { time: "10:00", type: "Express" },
        { time: "10:15", type: "Express" },
        { time: "10:30", type: "Express" },
        { time: "10:40", type: "Express" },
        { time: "10:55", type: "Express" },
        { time: "11:05", type: "Express" },
        { time: "11:15", type: "Express" },
        { time: "11:20", type: "Express" },
        { time: "11:30", type: "Express" },
        { time: "11:35", type: "Express" },
        { time: "11:45", type: "Express" },
        { time: "12:00", type: "Express" },
        { time: "12:15", type: "Express" },
        { time: "12:30", type: "Express" },
        { time: "12:45", type: "Express" },
        { time: "13:00", type: "Express" },
        { time: "13:15", type: "Express" },
        { time: "13:30", type: "Express" },
        { time: "13:45", type: "Express" },
        { time: "14:00", type: "Express" },
        { time: "14:15", type: "Express" },
        { time: "14:30", type: "Express" },
        { time: "14:40", type: "Express" },
        { time: "14:50", type: "Express" },
        { time: "15:00", type: "Express" },
        { time: "15:10", type: "Express" },
        { time: "15:15", type: "Express" },
        { time: "15:20", type: "Express" },
        { time: "15:30", type: "Express" },
        { time: "15:40", type: "Express" },
        { time: "15:45", type: "Express" },
        { time: "16:00", type: "Express" },
        { time: "16:15", type: "Express" },
        { time: "16:30", type: "Express" },
        { time: "16:45", type: "Express" },
        { time: "17:00", type: "Express" },
        { time: "17:15", type: "Express" },
        { time: "17:30", type: "Express" },
        { time: "17:45", type: "Express" },
        { time: "18:00", type: "Express" },
        { time: "18:30", type: "Express" },
        { time: "19:00", type: "Express" },
        { time: "19:45", type: "Express" },
        { time: "20:30", type: "Express" }
      ]
    },
    {
      id: "uppinangady",
      destination_en: "Uppinangady",
      destination_kn: "ಉಪ್ಪಿನಂಗಡಿ",
      platform: "8",
      bus_type: "Vegadhootha / Express",
      departures: [
        { time: "06:30", type: "Express" },
        { time: "08:30", type: "Express" },
        { time: "09:05", type: "Express" },
        { time: "09:45", type: "Express" },
        { time: "11:45", type: "Express" },
        { time: "12:05", type: "Express" },
        { time: "13:20", type: "Express" },
        { time: "13:45", type: "Express" },
        { time: "14:15", type: "Express" },
        { time: "15:45", type: "Express" },
        { time: "15:50", type: "Express" }
      ]
    },
    {
      id: "mangaluru",
      destination_en: "Mangaluru",
      destination_kn: "ಮಂಗಳೂರು",
      platform: "8",
      bus_type: "Vegadhootha / Express",
      departures: [
        { time: "05:00", type: "Express" },
        { time: "05:30", type: "Express" },
        { time: "06:00", type: "Express" },
        { time: "07:10", type: "Express" },
        { time: "07:30", type: "Express" },
        { time: "07:50", type: "Express" },
        { time: "08:15", type: "Express" },
        { time: "08:30", type: "Express" },
        { time: "08:45", type: "Express" },
        { time: "09:20", type: "Express" },
        { time: "10:00", type: "Express" },
        { time: "10:30", type: "Express" },
        { time: "11:00", type: "Express" },
        { time: "11:30", type: "Express" },
        { time: "12:30", type: "Express" },
        { time: "13:00", type: "Express" },
        { time: "14:00", type: "Express" },
        { time: "14:30", type: "Express" },
        { time: "15:00", type: "Express" },
        { time: "15:15", type: "Express" },
        { time: "15:30", type: "Express" },
        { time: "16:10", type: "Express" },
        { time: "16:45", type: "Express" },
        { time: "17:30", type: "Express" }
      ]
    },
    {
      id: "puttur",
      destination_en: "Puttur",
      destination_kn: "ಪುತ್ತೂರು",
      platform: "9",
      bus_type: "Samanya Sarige / Ordinary Bus",
      departures: [
        { time: "06:30", type: "Ordinary" },
        { time: "06:30", type: "Ordinary" },
        { time: "08:00", type: "Ordinary" },
        { time: "08:30", type: "Ordinary" },
        { time: "08:45", type: "Ordinary" },
        { time: "09:15", type: "Ordinary" },
        { time: "09:45", type: "Ordinary" },
        { time: "10:15", type: "Ordinary" },
        { time: "10:45", type: "Ordinary" },
        { time: "11:45", type: "Ordinary" },
        { time: "12:15", type: "Ordinary" },
        { time: "12:30", type: "Ordinary" },
        { time: "13:00", type: "Ordinary" },
        { time: "13:20", type: "Ordinary" },
        { time: "13:45", type: "Ordinary" },
        { time: "14:00", type: "Ordinary" },
        { time: "14:30", type: "Ordinary" },
        { time: "15:00", type: "Ordinary" },
        { time: "15:45", type: "Ordinary" },
        { time: "16:00", type: "Ordinary" },
        { time: "16:15", type: "Ordinary" },
        { time: "16:30", type: "Ordinary" },
        { time: "16:45", type: "Ordinary" },
        { time: "17:15", type: "Ordinary" },
        { time: "18:15", type: "Ordinary" }
      ]
    },
    {
      id: "sullia",
      destination_en: "Sullia",
      destination_kn: "ಸುಳ್ಯ",
      platform: "10",
      bus_type: "Samanya Sarige / Ordinary Bus",
      departures: [
        { time: "06:45", type: "Ordinary" },
        { time: "07:00", type: "Ordinary" },
        { time: "07:45", type: "Ordinary" },
        { time: "08:00", type: "Ordinary" },
        { time: "08:45", type: "Ordinary" },
        { time: "09:15", type: "Ordinary" },
        { time: "09:30", type: "Ordinary" },
        { time: "11:00", type: "Ordinary" },
        { time: "11:30", type: "Ordinary" },
        { time: "12:15", type: "Ordinary" },
        { time: "13:15", type: "Ordinary" },
        { time: "13:45", type: "Ordinary" },
        { time: "14:00", type: "Ordinary" },
        { time: "14:30", type: "Ordinary" },
        { time: "15:30", type: "Ordinary" },
        { time: "16:00", type: "Ordinary" },
        { time: "16:30", type: "Ordinary" },
        { time: "17:00", type: "Ordinary" },
        { time: "17:30", type: "Ordinary" },
        { time: "17:45", type: "Ordinary" },
        { time: "18:20", type: "Ordinary" },
        { time: "19:00", type: "Ordinary" }
      ]
    },
    {
      id: "balugodu-kollamogra",
      destination_en: "Balugodu / Kollamogra",
      destination_kn: "ಬಾಳುಗೋಡು / ಕೊಲ್ಲಮೊಗ್ರ",
      platform: "10",
      bus_type: "Samanya Sarige / Ordinary Bus",
      departures: [
        { time: "06:45", type: "Ordinary" },
        { time: "16:30", type: "Ordinary" },
        { time: "16:50", type: "Ordinary" }
      ]
    },
    {
      id: "kasaragod-sullia-panja",
      destination_en: "Kasaragodu / Sullia, Panja",
      destination_kn: "ಕಾಸರಗೋಡು, ಸುಳ್ಯ, ಪಂಜ",
      platform: "10",
      bus_type: "Samanya Sarige / Ordinary Bus",
      departures: [
        { time: "05:45", type: "Ordinary" },
        { time: "13:45", type: "Ordinary" }
      ]
    }
  ]
};
